export const nationalities = [
  'Cypriot',
  'Eritrean',
  'Liberian',
  'Bermudian',
  'Vatican',
  'Cook Islander',
  'Somali',
  'Zambian',
  'Venezuelan',
  'Turkmen',
  'Albanian',
  'Croatian',
  'British',
  'Sudanese',
  'East Timorese',
  'Azerbaijani',
  'Kenyan',
  'American Samoan',
  'Ivorian',
  'Senegalese',
  'Vietnamese',
  'Salvadoran',
  'Afghan',
  'Saint Martin Islander',
  'Latvian',
  'Guatemalan',
  'Kuwaiti',
  'Sao Tomean',
  'Kirghiz',
  'Polish',
  'Guamanian',
  'Ghanaian',
  'Lithuanian',
  'Armenian',
  'Channel Islander',
  'Grenadian',
  'Tadzhik',
  'Ethiopian',
  'Sahrawi',
  'Moroccan',
  'Puerto Rican',
  'Christmas Islander',
  'New Zealander',
  'Bruneian',
  'Guianan',
  'Niuean',
  'Romanian',
  'Belarusian',
  'Cameroonian',
  'Czech',
  'Saint Barthélemy Islander',
  'Greek',
  'Malian',
  'Martinican',
  'French',
  'Pakistani',
  'Peruvian',
  'Barbadian',
  'Greenlandic',
  'Saint-Pierrais, Miquelonnais',
  'Chadian',
  'Hungarian',
  'Comoran',
  'Bangladeshi',
  'Tokelauan',
  'Fijian',
  'Chinese',
  'Colombian',
  'Algerian',
  'Maldivan',
  'Malaysian',
  'Caymanian',
  'Spanish',
  'Irish',
  'Estonian',
  'Paraguayan',
  'Uruguayan',
  'South African',
  'Saint Lucian',
  'Ni-Vanuatu',
  'Finnish',
  'Swedish',
  'Indian',
  'Lebanese',
  'Chilean',
  'Norfolk Islander',
  'Montserratian',
  'Australian',
  'Belizean',
  'Guyanese',
  'Mongolian',
  'Tuvaluan',
  'Equatorial Guinean',
  'Kittitian or Nevisian',
  'Nepalese',
  'Taiwanese',
  'Beninese',
  'Bulgarian',
  'Moldovan',
  'Manx',
  'Bhutanese',
  'Cambodian',
  'Antiguan, Barbudan',
  'Haitian',
  'Cape Verdian',
  'Georgian',
  'Burundian',
  'Bahamian',
  'Mauritian',
  'Libyan',
  'Malawian',
  'Mexican',
  'Swazi',
  'Papua New Guinean',
  'Dominican',
  'Liechtensteiner',
  'Russian',
  'Israeli',
  'Singaporean',
  'Ugandan',
  'Slovak',
  'Tongan',
  'Emirati',
  'Mahoran',
  'Surinamer',
  'Uzbekistani',
  'Saudi Arabian',
  'Egyptian',
  'Italian',
  'Malagasy',
  'New Caledonian',
  'Canadian',
  'Virgin Islander',
  'Marshallese',
  'Mauritanian',
  'Gambian',
  'Trinidadian',
  'Seychellois',
  'Japanese',
  'Brazilian',
  'Syrian',
  'Saint Helenian',
  'Andorran',
  'Iranian',
  'Togolese',
  'Maltese',
  'South Korean',
  'Samoan',
  'German',
  'Nigerien',
  'Jamaican',
  'Nicaraguan',
  'Guinean',
  'Anguillian',
  'Ålandish',
  'Belgian',
  'Portuguese',
  'Danish',
  'Filipino',
  'Wallis and Futuna Islander',
  'Austrian',
  'Guinea-Bissauan',
  'Monegasque',
  'Namibian',
  'American Islander',
  'Costa Rican',
  'Bosnian, Herzegovinian',
  'Macanese',
  'Mozambican',
  'Réunionese',
  'Montenegrin',
  'North Korean',
  'American',
  'Ukrainian',
  'Iraqi',
  'South Georgian South Sandwich Islander',
  'Angolan',
  'Sierra Leonean',
  'Micronesian',
  'Cuban',
  'Turks and Caicos Islander',
  'Serbian',
  'Ecuadorean',
  'Faroese',
  'Antarctican',
  'Palestinian',
  'Turkish',
  'I-Kiribati',
  'Kazakhstani',
  'Gibraltar',
  'Palauan',
  'Qatari',
  'Swiss',
  'French Polynesian',
  'Pitcairn Islander',
  'Jordanian',
  'Burmese',
  'Thai',
  'Dutch',
  'Aruban',
  'Guadeloupian',
  'Nigerian',
  'Bahraini',
  'Laotian',
  'Cocos Islander',
  'Djibouti',
  'Solomon Islander',
  'Heard and McDonald Islander',
  'Sammarinese',
  'Luxembourger',
  'St. Maartener',
  'Falkland Islander',
  'Central African',
  'Motswana',
  'Curaçaoan',
  'Norwegian',
  'Gabonese',
  'Zimbabwean',
  'Mosotho',
  'Slovene',
  'Argentine',
  'Burkinabe',
  'Yemeni',
  'Congolese',
  'Omani',
  'Indonesian',
  'Nauruan',
  'Rwandan',
  'Macedonian',
  'Kosovar',
  'Tunisian',
  'South Sudanese',
  'Honduran',
  'Saint Vincentian',
  'Sri Lankan',
  'Hong Konger',
];
